// <auto-generated />
using InvoicePro.Data.SQLite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvoicePro.Data.Migrations
{
    [DbContext(typeof(BillingDbContext))]
    [Migration("20260902000000_AddEmailAndTaxPercentage")]
    partial class AddEmailAndTaxPercentage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("InvoicePro.Models.Company", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<string>("AuthorizedSignatoryText").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("BankAccount").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("BankBranch").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("BankName").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Email").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("GSTIN").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("IFSC").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Name").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Phone").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("RegisteredOffice").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("SalesOffice").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("State").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("StateCode").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("TermsAndConditions").IsRequired().HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.ToTable("Companies");
                });

            modelBuilder.Entity("InvoicePro.Models.Product", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<string>("Description").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Fit").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("HSN").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("ProductCode").IsRequired().HasColumnType("TEXT");
                    b.Property<decimal>("Rate").HasColumnType("TEXT");
                    b.Property<string>("Size").IsRequired().HasColumnType("TEXT");
                    b.Property<decimal>("TaxPercentage").HasColumnType("TEXT");
                    b.Property<string>("UOM").IsRequired().HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
